apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "apisix-openshift.fullname" . }}-scc-anyuid
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "apisix-openshift.fullname" . }}-scc-anyuid
subjects:
- kind: ServiceAccount
  name: {{ .Values.apisix.serviceAccount.name | default "default" }}
  namespace: {{ .Release.Namespace }}
